name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        # Remove cache: 'npm' since we don't have lock file

    - name: Setup JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install npm dependencies
      run: npm install  # ✅ Changed from npm ci

    - name: Make Gradlew executable
      run: chmod +x android/gradlew

    - name: Build Android Release APK
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload APK to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: string-art-app-release
        path: android/app/build/outputs/apk/release/app-release.apk
