name: Build APK

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleRelease
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
